default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_tutorial_development

test:
  <<: *default
  database: rails_tutorial_test

production:
  primary:
    <<: *default
    database: rails_tutorial_production
  cache:
    <<: *default
    database: rails_tutorial_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: rails_tutorial_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: rails_tutorial_production_cable
    migrations_paths: db/cable_migrate
